## Bedingte Wahrscheinlichkeiten 

### Bedingte Wahrscheinlichkeit

:::{.block}
#### Def.: **Bedingte Wahrscheinlichkeit**  
Die *bedingte Wahrscheinlichkeit von $A$ gegeben $B$* für Ereignisse $A, B \subseteq \Omega$ mit $P(B) > 0$ 
ist 
$$P(A|B) := \frac {P(A \cap B)}{P(B)}$$
:::

Interpretation:

- "Wie wahrscheinlich ist A *wenn B bereits eingetreten* ist?"
- "Wie wahrscheinlich ist A *unter der Annahme, dass B* der Fall ist?"

Intuition:  

- "In welchem Anteil von den Fällen, in denen $B$ eintritt, tritt auch $A$ ein?"
- "Welchen *Anteil* an der Wahrscheinlichkeit für Bedingung $B$ haben die Elementarereignisse, die auch Teil des interessierenden Ereignisses $A$ sind?"


\note[item]{$P(A|B) :$ "W.keit für A wenn B schon eingetreten ist/unter der Annahme dass B eingetreten ist"}

### Beispiel: Würfelwurf

$G:=$ "Würfelergebnis gerade Zahl",  
$F:=$ "Würfelergebnis mindestens 5"  
$S:=$ "Würfelergebnis ist 6"

Dann z.B.: 
\begin{align*}
\implies P(F|G) &= \frac{1}{3}\\
 P(G|F) &= \frac{1}{2} \\
 P(S|\bar G) &= 0 \\ 
 P(G|S) &= 1 \\
\end{align*}

### Eigenschaften von bedingten Wahrscheinlichkeiten 

\begin{align*}
 P(B|B) & =  1 \;\; \text{(Sicheres Ereignis)}\\
 P(\bar{B}|B)& =  0 \;\;\text{(Unmögliches Ereignis)}\\
 P(A|B) & \geq 0 \mbox{ für beliebige }A \subseteq \Omega \;\; \text{(Positivität)}\\
\intertext{Außerdem gelten alle Aussagen über Wahrscheinlichkeiten \textbf{bei fester Bedingung} auch für \textit{bedingte} Wahrscheinlichkeiten, z.B.:}
P((A_1 \cup A_2)|B) & = P(A_1|B) + P(A_2|B) \mbox{ für $A_1$ und $A_2$ disjunkt. (Additivität)}  \\
\intertext{
$\implies$ Die bedingten Wahrscheinlichkeiten  $P(A|B)$ für $A \subseteq \Omega$ definieren \textit{bei fester Bedingung
$B$} einfach eine \textbf{Wahrscheinlichkeitsverteilung über die neue, kleinere stochastische Grundgesamtheit $B \subset \Omega$.}}
\intertext{Mehrfaches Bedingen $\implies$ Bedingen auf den \emph{Schnitt} der Bedingungen:}
P\big((A|B)|C \big) &= P\big(A | (B \cap C)\big) 
\end{align*}




### Beispiel: Skat 

Definiere   

$A:=$ "Mindestens eine der acht Karokarten liegt im Skat"  
$B:=$ "Spieler 1 erhält beim Austeilen keine der acht Karokarten"

Berechne $P(A)$ und $P(A|B)$ und vergleiche diese.

\note[item]{
&& P(A)  = 1 - P(\bar{A})\\
& = & 1 - \frac{\binom{8}{0}\binom{24}{2}}{\binom{32}{2}}\\
& = & 1 - \frac{24!/22!}{32!/30!} = 1 - \frac{24 \cdot 23}{32 \cdot 31}\\
&=& 0,4435 \\
&& P(A|B)  =  1 - P(\bar{A}|B)\\
& = & 1 - \frac{\binom{8}{0}\binom{14}{2}}{\binom{22}{2}}\\
& = & 1 - \frac{14 \cdot 13}{22 \cdot 21}\\
& = & 0,\overline{60}
"gegeben B" bedeutet 22 karten übrig, davon 8 Karo.

Alternativ: 
Omega = "alle kartenkombinationen für spieler 1 und skat"
|Omega| = \binom{32}{10}\binom{22}{2}
|\bar A \cup B| = \binom{24}{10}\binom{8}{0}\binom{14}{2}
|B| =  \binom{24}{10}\binom{22}{2}
}

### Multiplikationssatz 

Für beliebige Ereignisse $A_1, A_2, ..., A_n$ mit
$P(A_1 \cap A_2 \cap ... \cap A_n) > 0$ gilt:
$$ P(A_1 \cap A_2 \cap ... \cap A_n) = P(A_1)\cdot P(A_2|A_1) \cdot P(A_3|A_1 \cap A_2) \cdot ... \cdot P(A_n|A_1 \cap ... \cap A_{n-1})$$
wobei man die rechte Seite offensichtlich auch in jeder anderen möglichen Reihenfolge faktorisieren kann. 

\vskip 3em 
\small
Alternative informelle Schreibweise:  
$$P(A_1, A_2) := P(A_1 \cap A_2)$$  
insbesondere gilt also z.B.  
$P(A_1 , A_2)  =  P(A_1)\cdot P(A_2|A_1)$,  
$P(A_1 , A_2 , A_3) = P(A_1)\cdot P(A_2|A_1) \cdot P(A_3|A_1, A_2)$, ...

\note[item]{ Beweis: Definition bed. W.keit}

### Satz von der totalen Wahrscheinlichkeit 

:::{.block}
#### Def: **Disjunkte Zerlegung (Partition)**  
Die Mengen $B_1, B_2, ..., B_n$ bilden eine *disjunkte Zerlegung* von $\Omega$, falls  

- $B_1, B_2, ..., B_n$ paarweise disjunkt: $B_i \cap B_j = \emptyset \quad \forall i \neq j$
- und $B_1 \cup B_2 \cup ... \cup B_n = \Omega$
:::

:::{.block}
#### Satz von der totalen Wahrscheinlichkeit  
Sei $B_1, B_2, ..., B_n$ eine *disjunkte Zerlegung* von $\Omega$ mit $P(B_i) > 0$ für $i=1,..., n$, dann gilt für jedes $A \subseteq \Omega$:
$$ P(A) = \sum_{i=1}^n P(A|B_i) \cdot P(B_i) $$
:::

### Wichtiger Spezialfall 

Insbesondere gilt
$$ P(A) = P(A|B)P(B) + P(A|\bar{B})P(\bar{B})$$
da $B, \bar{B}$  eine disjunkte Zerlegung von $\Omega$ ist.

\note[item]{ Beweis: Definition bed. W.keit einsetzen}
